steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt:1.10.1-jdk-11'
  args: ['dist']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/trello-changelog',  '.']
images:
- 'eu.gcr.io/$PROJECT_ID/trello-changelog'
